sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: O9QuQzrm/b+1Ers+HjMc6l+yvxbljvZ478Bx8NHChsMjQjQ09Aw1mleoxUeoo2DorGb4QN+4h82qn9WQtXBdBO7pswtHlzMltiP3+fr+14npu1L9oJgp9Wt82uwoihlpB5/dv3vfIXS5BHNZpptd2/+cpHgUFC8y5+JygnW1UlZHHhFHZZiMuq5RSjdjCE1MtqN5LIVMZDI6INDrlbs5DGhw3Do3R/SPIs0pFSqeU8Xdu7/NLKbW6T3Z7FH7tP5qxKYmS9TP7/CmgG9j/b7A2acAvsbe0Y6vtcwTGyibrDiJyc5/Npyff5cVZRbC5HaTDPv4PzwihHTDPlpZVsSZPxk4QFDXRa356DypVOcgUVeYotHcbWXVj+jsNE8q0lm5bpqOc7QyPB/V6lK3iZ8i2YRRY68kFyV6908NQg8kakq40ItMrWHNkFgqJXb+UoBPIcv1qqMDeph8frEzJI4hXpAfwfpwjd5n8WsTh99MGDDrknQj67XXkFYvIxPD7OkYbg9HdtLEegV8SvDMy29wGDti5t1o7PepgdBSfd04bIABrKYEemNu3cvT4jn9BC8LuI5azBzi1RwG6cfIgvoNXXO1G+Ca1gB4wQS0I2+7L+n1krzxslTZGZ1lHIGL0jYx3GJ/KPESiAHISOewxhLVKj1Ziav3Sae6jJamY2iGeH8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/John-Marshall-and-the-Constitution-a-Chronicle-of-the-Supreme-Court_3291
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy